### ISSUE TITLE
crash..

### ISSUE THREAD

**Issue by Tntdruid** [EmosewaPixel/GregsConstruct#10]
java.lang.NoSuchMethodError: gregtech.api.recipes.RecipeMap.findRecipe(JLjava/util/List;Ljava/util/List;)Lgregtech/api/recipes/Recipe;
	at gregsconstruct.GtRecipes.removeRecipesByInputs(GtRecipes.java:60)
	at gregsconstruct.GtRecipes.init(GtRecipes.java:21)
	at gregsconstruct.GregsConstruct$events.registerRecipes(GregsConstruct.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_606_events_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:629)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

GregsConstruct-1.12.2-1.0.1.jar
gregtech-1.12.2-1.8.4.419.jar

**Comment by FrostCreeper07** [comment]
I have the same error as the op so until somebody can tell us what's going on i've removed it from my pack

**Comment by skwerlman** [comment]
this caused by a too-new gtce. this addon is written for gtce 1.6, yall are using gtce 1.8.4 which has a different api

theres a pr to support 1.8 (see #6), but 1.8.4 seems to have additional changes beyond what the pr changes

**Comment by hjae78** [comment]
Anyone looking for a working version look under my repositories

**Comment by Tntdruid** [comment]
@hjae78 Thanks!

**Comment by DanHCraft** [comment]
> Anyone looking for a working version look under my repositories

@hjae78 Your download link is invalid, because dropbox shows a file deleted to me!

**Comment by LuizLoyola** [comment]
> > Anyone looking for a working version look under my repositories
> 
> @hjae78 Your download link is invalid, because dropbox shows a file deleted to me!

@DanHCraft I'm trying to build from his repo, got a few errors because the versions are so old (even Gradle throws some errors with his build.gradle)

Will report back with the compiled .jar

**Comment by LuizLoyola** [comment]
[GregsConstruct-1.12.2-1.0.3-UNOFFICIAL.jar.zip](https://github.com/TheLimePixel/GregsConstruct/files/7836896/GregsConstruct-1.12.2-1.0.3-UNOFFICIAL.jar.zip)

Here it is, just changed some Gradle stuff and built it with the latest GTCE version. Works fine on my MC instance

**Comment by DanHCraft** [comment]
You are an angel, thank you very much \^-^/. I tried it by my self also earlier, but failed with the dependencies of multiconnect.
